version: '3.8'

services:
  eclipse-temurin:
    image: eclipse-temurin:latest
    container_name: eclipse-temurin
    volumes:
      - /Users/dimitarpaunov/people-sphere-service/interview-service/target:/app
    command: ["java", "-jar", "/app/interview-service-0.1.0.jar"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - eclipse-temurin

volumes:
  certs: